---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: apache
spec:
  routes:
    - match:
        http:
          queryParam:
            - name: "version"
              exact: "v1"
      destination:
        service: apache
        serviceSubset: v1

    - match:
        http:
          queryParam:
            - name: "version"
              exact: "v2"
      destination:
        service: apache
        serviceSubset: v2
