---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: apache
spec:
  defaultSubset: v2
  subsets:
    v1:
      filter: 'Service.Meta.version == 1'
    v2:
      filter: 'Service.Meta.version == 2'
